[package]
name = "jwt"
version = "0.1.0"
authors = ["Aleksey Bilogur <aleksey@residentmar.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.11.13"
base64 = "0.13.0"